Validate that diff caused failure in actions

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -42,10 +42,46 @@ jobs:
         java-version: '11'
         distribution: 'temurin'
         cache: maven # Cache dependencies
-
-    - name: Build with Maven
+    - name: Build sourcecodeanalyzer packages
       run: mvn clean package
-    - name: Execute module
+    - name: Execute sourcecodeanazyer module
       run: java -jar ~/work/seip-lab/seip-lab/sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/test/resources/TestClass.java regex local ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/metrics_csv csv
     - name: Compare outputs
-      run: diff ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/metrics_csv.csv ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/expected.csv
+      run: |
+        diff ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/metrics_csv.csv ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/expected.csv
+        DIFF_EXIT_CODE=$?
+        # If the exit code is non-zero, fail the action
+        if [ $DIFF_EXIT_CODE -ne 0 ]; then
+          echo "Differences found"
+          exit 1
+        else
+          echo "No differences found."
+        fi
+
+  integration-test-with-failure:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3 # Set up Java
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          cache: maven # Cache dependencies
+      - name: Build sourcecodeanalyzer packages
+        run: mvn clean package
+      - name: Execute sourcecodeanazyer module
+        run: java -jar ~/work/seip-lab/seip-lab/sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/test/resources/TestClass.java regex local ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/metrics_csv csv
+      - name: Compare outputs
+        run: |
+          diff ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/metrics_csv.csv ~/work/seip-lab/seip-lab/sourcecodeanalyzer/src/main/resources/expected-failure.csv
+          DIFF_EXIT_CODE=$?
+          # If the exit code is non-zero, fail the action
+          if [ $DIFF_EXIT_CODE -ne 0 ]; then
+            echo "Differences found"
+            exit 1
+          else
+            echo "No differences found."
+          fi
